# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

channel_name = "#fastlane"  
access_token = "token" 

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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" 
end


platform :android do
  desc "Run all tests"
  lane :test do
    gradle(task: "test")
    slack(message: "Test executed successfully! :beer:")
    #upload_to_slack() 
  end

  #desc "Submit a new Beta Build to Crashlytics Beta"
  #lane :beta do
  #  gradle(task: "clean assembleRelease")
  #  crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  #end

  #develop
  desc "Deploy a new Develop Debug APK to " + channel_name + " Slack channel"
  lane :developDebug do    
    gradle(task: "assembleDevelopDebug")   
    slack(message: "Build Successful! :beers:")   
    upload_to_slack() 
  end

  desc "Deploy a new Develop Release APK to " + channel_name + " Slack channel"
  lane :developRelease do |options|
    gradle(task: "assembleDevelopRelease")   
    slack(message: "Build Successful! :beers:")   
    upload_to_slack() 
  end

  #qa
  desc "Deploy a new Qa Debug APK to " + channel_name + " Slack channel"
  lane :qaDebug do    
    gradle(task: "assembleQaDebug")   
    slack(message: "Build Successful! :beers:")   
    upload_to_slack() 
  end

  desc "Deploy a new Qa Release APK to " + channel_name + " Slack channel"
  lane :qaRelease do |options|
    gradle(task: "assembleQaRelease")   
    slack(message: "Build Successful! :beers:")   
    upload_to_slack() 
  end

  lane :release do    
    desc "Deploy release APK"
    gradle(task: "assembleRelease")   
    slack(message: "Build Successful! :beers:")   
    upload_to_slack() 
  end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end

  desc "Upload the APK to Slack channel"  
  private_lane :upload_to_slack do |options|    
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    file_name = file_path.gsub(/\/.*\//,"")
    #channel_name = "#fastlane"    
    sh "echo Uploading " + file_name + " to Slack"  
    sh "curl https://slack.com/api/files.upload -F token=\"" + access_token + "\" -F channels=\"" + channel_name + "\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + file_path  
  end

  #after_all do |lane|   
    #slack(      
    #  message: "successful deploy"      
    #  )   
    #end 
    
  error do |lane, exception|      
    slack(        
      message: exception.message,      
      success:false     
    )   
  end 

end
